version: 1.0.{build}
build_cloud: Process
max_jobs: 1
image: Visual Studio 2017
clone_depth: 1
build_script:
- ps: |
    dotnet build TestConsoleApp
    dotnet publish TestConsoleApp -c Release
    dotnet pack TestConsoleApp -c Release
- ps: Push-AppveyorArtifact TestConsoleApp.sln

test: off

artifacts:
- path: TestConsoleApp\bin\release\netcoreapp2.2\publish\
- path: TestConsoleApp\bin\Release\TestConsoleApp.1.0.0.nupkg
  name: nuget-pack
