version: 1.0.{build}
build_cloud: Process
max_jobs: 1
image: Visual Studio 2017
clone_depth: 1

#dotnet_csproj:
#  patch: true
#  file: '**\*.csproj'
#  version: '{version}'
#  package_version: '{version}'
#  assembly_version: '{version}'
#  file_version: '{version}'
#  informational_version: '{version}'

build_script:
- ps: |
    dotnet build TestConsoleApp
    dotnet publish TestConsoleApp -c Release
    dotnet pack TestConsoleApp -c Release
- ps: Push-AppveyorArtifact TestConsoleApp.sln

test: off

artifacts:
- path: TestConsoleApp\bin\release\netcoreapp2.2\publish\
- path: TestConsoleApp\bin\Release\TestConsoleApp.*.nupkg
  name: nuget-pack

#deploy:
#- provider: NuGet
#  server: http://localhost:5000/nuget/appveyor-ocxxelj1qm4c
#  api_key:
#    secure: 0t8Gd2o5oQcXgbSFrqoP2f4uSrsxS68ZjGfrJMCRWQA=
#  skip_symbols: true
